export {default as Categories} from './Categories'
export {default as Products} from './Products'
export {default as ProductsDetails} from './ProductsDetails'
export {default as Cart} from './Cart'
export {default as Orders} from './Orders'